// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKXQhZfe7DPmyNCipdXzVGONmd646nH4',
    appId: '1:75154356720:web:b76a37ff3dbd81a0bfc535',
    messagingSenderId: '75154356720',
    projectId: 'chat-app-7fef8',
    authDomain: 'chat-app-7fef8.firebaseapp.com',
    storageBucket: 'chat-app-7fef8.appspot.com',
    measurementId: 'G-GB398E6ZP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvGVd0wHsNn4KwovH5IRcMgvmt54Bf1M',
    appId: '1:75154356720:android:e871b2ae0fcf6699bfc535',
    messagingSenderId: '75154356720',
    projectId: 'chat-app-7fef8',
    storageBucket: 'chat-app-7fef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEZiHBM3wPjjZ_3If_L10oLFJ3d_SC2BI',
    appId: '1:75154356720:ios:9bbd15b0af349a76bfc535',
    messagingSenderId: '75154356720',
    projectId: 'chat-app-7fef8',
    storageBucket: 'chat-app-7fef8.appspot.com',
    iosClientId: '75154356720-1cma0f0j4lnrjundl0qv2dsf9839afui.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEZiHBM3wPjjZ_3If_L10oLFJ3d_SC2BI',
    appId: '1:75154356720:ios:01e21e6809d225dcbfc535',
    messagingSenderId: '75154356720',
    projectId: 'chat-app-7fef8',
    storageBucket: 'chat-app-7fef8.appspot.com',
    iosClientId: '75154356720-68qfk1l7fdjbbjt1s7an6isa5br9613e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
